#!/usr/bin/env sh
#
# Usage:
#
# ./gif-maker video.mp4 out.gif
#
# Produces a 320x167, animated gif, 10fps, 10ms spaced
#
# brew install gifsicle imagemagick
# # or
# dnf install gifsicle ImageMagick ffmpeg

set -e

in=$1
out=$2

main() {
    ffmpeg -y -i $in -vf fps=10,scale=320:-1:flags=lanczos,palettegen palette.png
    ffmpeg -i $in -i palette.png -filter_complex "fps=10,scale=320:-1:flags=lanczos[x];[x][1:v]paletteuse" $out
}

main
